
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.Map;
import org.testng.Assert;
import org.testng.annotations.Test;

/**
 * Test suite for the LCM class.
 * <p>
 * The provided test suite is correct and complete. You should not need to modify it. However, you
 * should understand it. You may need to augment or write test suites for later MPs.
 *
 * The simpler tests at the top are to aid your debugging. Once they pass, the full test suite at the bottom
 * will be run.
 *
 * @see <a href="https://cs125.cs.illinois.edu/MP/0/">MP0 Documentation</a>
 */
@Test
public class LCMTest {

    /** Timeout for simple tests. */
    private static final int SIMPLE_TEST_TIMEOUT = 100;

    @Test(timeOut=SIMPLE_TEST_TIMEOUT)
    public void testLCMWithGoodPositiveInputs() {
        Assert.assertEquals(LCM.lcm(4, 6), 12);
        Assert.assertEquals(LCM.lcm(1, 7), 7);
        Assert.assertEquals(LCM.lcm(9, 9), 9);
        Assert.assertEquals(LCM.lcm(7, 11), 77);
    }

    @Test(timeOut=SIMPLE_TEST_TIMEOUT)
    public void testLCMWithGoodNegativeInputs() {
        Assert.assertEquals(LCM.lcm(4, -5), 20);
        Assert.assertEquals(LCM.lcm(-2, -7), 14);
        Assert.assertEquals(LCM.lcm(-9, 9), 9);
        Assert.assertEquals(LCM.lcm(-7, -13), 91);
    }

    @Test(timeOut=SIMPLE_TEST_TIMEOUT)
    public void testLCMWithBadInputs() {
        Assert.assertEquals(LCM.lcm(4, 0), LCM.LCM_INVALID);
        Assert.assertEquals(LCM.lcm(0, -7), LCM.LCM_INVALID);
        Assert.assertEquals(LCM.lcm(0, 0), LCM.LCM_INVALID);
    }

    /** Timeout for grading test. Solution takes 96 ms. */
    private static final int GRADING_TEST_TIMEOUT = 2000;

    /**
     * Grade with precomputed values.
     */
    @Test(timeOut = GRADING_TEST_TIMEOUT)
    public void gradeLCM() {
        for (Map.Entry<ArrayList<Integer>, Integer> precomputed : PRECOMPUTED_RESULTS.entrySet()) {
            ArrayList<Integer> input = precomputed.getKey();
            Integer output = precomputed.getValue();

            /*
             * Check LCM in both directories.
             */
            Assert.assertEquals(LCM.lcm(input.get(0), input.get(1)),
                    (int) output,
                    String.format("LCM of %d and %d is incorrect", input.get(0), input.get(1)));
            Assert.assertEquals(LCM.lcm(input.get(1), input.get(0)),
                    (int) output,
                    String.format("LCM of %d and %d is incorrect", input.get(0), input.get(1)));
        }
    }

    /** Pre-computed testing values. */
    private static final Map<ArrayList<Integer>, Integer> PRECOMPUTED_RESULTS =
            new LinkedHashMap<>() {
                {
                    put(new ArrayList<>() {
                        {
                            add(6);
                            add(4);
                        }
                    }, 12);
                    put(new ArrayList<>() {
                        {
                            add(-6);
                            add(3);
                        }
                    }, 6);
                    put(new ArrayList<>() {
                        {
                            add(0);
                            add(4);
                        }
                    }, LCM.LCM_INVALID);
                    put(new ArrayList<>() {
                        {
                            add(6);
                            add(0);
                        }
                    }, LCM.LCM_INVALID);
                    /* BEGIN AUTOGENERATED CODE */
                    put(new ArrayList<>() {
                        {
                            add(-28974);
                            add(-20094);
                        }
                    }, 97033926);
                    put(new ArrayList<>() {
                        {
                            add(-26612);
                            add(6602);
                        }
                    }, 87846212);
                    put(new ArrayList<>() {
                        {
                            add(-20244);
                            add(15094);
                        }
                    }, 152781468);
                    put(new ArrayList<>() {
                        {
                            add(-14814);
                            add(3445);
                        }
                    }, 51034230);
                    put(new ArrayList<>() {
                        {
                            add(-16489);
                            add(25672);
                        }
                    }, 423305608);
                    put(new ArrayList<>() {
                        {
                            add(-16500);
                            add(-8781);
                        }
                    }, 48295500);
                    put(new ArrayList<>() {
                        {
                            add(-31456);
                            add(-26813);
                        }
                    }, 843429728);
                    put(new ArrayList<>() {
                        {
                            add(-7693);
                            add(-15339);
                        }
                    }, 118002927);
                    put(new ArrayList<>() {
                        {
                            add(31913);
                            add(-2775);
                        }
                    }, 88558575);
                    put(new ArrayList<>() {
                        {
                            add(-3874);
                            add(23942);
                        }
                    }, 46375654);
                    put(new ArrayList<>() {
                        {
                            add(-572);
                            add(9281);
                        }
                    }, 5308732);
                    put(new ArrayList<>() {
                        {
                            add(25721);
                            add(13042);
                        }
                    }, 335453282);
                    put(new ArrayList<>() {
                        {
                            add(-28398);
                            add(-31308);
                        }
                    }, 148180764);
                    put(new ArrayList<>() {
                        {
                            add(26699);
                            add(22690);
                        }
                    }, 605800310);
                    put(new ArrayList<>() {
                        {
                            add(-17978);
                            add(-21025);
                        }
                    }, 377987450);
                    put(new ArrayList<>() {
                        {
                            add(25390);
                            add(-4335);
                        }
                    }, 22013130);
                    put(new ArrayList<>() {
                        {
                            add(-114);
                            add(-25098);
                        }
                    }, 476862);
                    put(new ArrayList<>() {
                        {
                            add(-13767);
                            add(18092);
                        }
                    }, 249072564);
                    put(new ArrayList<>() {
                        {
                            add(-14882);
                            add(-18680);
                        }
                    }, 138997880);
                    put(new ArrayList<>() {
                        {
                            add(17371);
                            add(-16396);
                        }
                    }, 284814916);
                    put(new ArrayList<>() {
                        {
                            add(-28829);
                            add(-11656);
                        }
                    }, 336030824);
                    put(new ArrayList<>() {
                        {
                            add(-28478);
                            add(-8764);
                        }
                    }, 124790596);
                    put(new ArrayList<>() {
                        {
                            add(9051);
                            add(-29914);
                        }
                    }, 270751614);
                    put(new ArrayList<>() {
                        {
                            add(-6015);
                            add(27888);
                        }
                    }, 55915440);
                    put(new ArrayList<>() {
                        {
                            add(24911);
                            add(-14529);
                        }
                    }, 12480411);
                    put(new ArrayList<>() {
                        {
                            add(29771);
                            add(21608);
                        }
                    }, 643291768);
                    put(new ArrayList<>() {
                        {
                            add(-264);
                            add(27199);
                        }
                    }, 7180536);
                    put(new ArrayList<>() {
                        {
                            add(19616);
                            add(18528);
                        }
                    }, 11357664);
                    put(new ArrayList<>() {
                        {
                            add(26318);
                            add(4309);
                        }
                    }, 113404262);
                    put(new ArrayList<>() {
                        {
                            add(4315);
                            add(32599);
                        }
                    }, 140664685);
                    put(new ArrayList<>() {
                        {
                            add(13971);
                            add(-7046);
                        }
                    }, 98439666);
                    put(new ArrayList<>() {
                        {
                            add(-6931);
                            add(-10610);
                        }
                    }, 73537910);
                    put(new ArrayList<>() {
                        {
                            add(31260);
                            add(1249);
                        }
                    }, 39043740);
                    put(new ArrayList<>() {
                        {
                            add(18566);
                            add(-19879);
                        }
                    }, 369073514);
                    put(new ArrayList<>() {
                        {
                            add(-4319);
                            add(-21303);
                        }
                    }, 92007657);
                    put(new ArrayList<>() {
                        {
                            add(-26569);
                            add(-3977);
                        }
                    }, 105664913);
                    put(new ArrayList<>() {
                        {
                            add(-4689);
                            add(27674);
                        }
                    }, 129763386);
                    put(new ArrayList<>() {
                        {
                            add(-29030);
                            add(3576);
                        }
                    }, 51905640);
                    put(new ArrayList<>() {
                        {
                            add(20528);
                            add(18779);
                        }
                    }, 385495312);
                    put(new ArrayList<>() {
                        {
                            add(-18571);
                            add(-1419);
                        }
                    }, 26352249);
                    put(new ArrayList<>() {
                        {
                            add(-5560);
                            add(-1529);
                        }
                    }, 61160);
                    put(new ArrayList<>() {
                        {
                            add(-1847);
                            add(28084);
                        }
                    }, 51871148);
                    put(new ArrayList<>() {
                        {
                            add(-10458);
                            add(27536);
                        }
                    }, 143985744);
                    put(new ArrayList<>() {
                        {
                            add(-8508);
                            add(16563);
                        }
                    }, 46972668);
                    put(new ArrayList<>() {
                        {
                            add(22301);
                            add(-2669);
                        }
                    }, 59521369);
                    put(new ArrayList<>() {
                        {
                            add(-1539);
                            add(19102);
                        }
                    }, 29397978);
                    put(new ArrayList<>() {
                        {
                            add(-30962);
                            add(17158);
                        }
                    }, 265622998);
                    put(new ArrayList<>() {
                        {
                            add(20332);
                            add(31620);
                        }
                    }, 9454380);
                    put(new ArrayList<>() {
                        {
                            add(-20352);
                            add(-28744);
                        }
                    }, 73124736);
                    put(new ArrayList<>() {
                        {
                            add(10514);
                            add(27399);
                        }
                    }, 288073086);
                    put(new ArrayList<>() {
                        {
                            add(-21707);
                            add(-9323);
                        }
                    }, 202374361);
                    put(new ArrayList<>() {
                        {
                            add(16772);
                            add(-22680);
                        }
                    }, 13585320);
                    put(new ArrayList<>() {
                        {
                            add(-31091);
                            add(11232);
                        }
                    }, 349214112);
                    put(new ArrayList<>() {
                        {
                            add(-11362);
                            add(-2172);
                        }
                    }, 12339132);
                    put(new ArrayList<>() {
                        {
                            add(-7457);
                            add(-28541);
                        }
                    }, 212830237);
                    put(new ArrayList<>() {
                        {
                            add(-27368);
                            add(-21648);
                        }
                    }, 6732528);
                    put(new ArrayList<>() {
                        {
                            add(-10486);
                            add(25513);
                        }
                    }, 267529318);
                    put(new ArrayList<>() {
                        {
                            add(16511);
                            add(-8579);
                        }
                    }, 141647869);
                    put(new ArrayList<>() {
                        {
                            add(2948);
                            add(30837);
                        }
                    }, 90907476);
                    put(new ArrayList<>() {
                        {
                            add(15801);
                            add(2433);
                        }
                    }, 12814611);
                    put(new ArrayList<>() {
                        {
                            add(15001);
                            add(28994);
                        }
                    }, 62134142);
                    put(new ArrayList<>() {
                        {
                            add(22921);
                            add(18763);
                        }
                    }, 430066723);
                    put(new ArrayList<>() {
                        {
                            add(-26037);
                            add(18352);
                        }
                    }, 477831024);
                    put(new ArrayList<>() {
                        {
                            add(29724);
                            add(-10805);
                        }
                    }, 321167820);
                    put(new ArrayList<>() {
                        {
                            add(17446);
                            add(17540);
                        }
                    }, 153001420);
                    put(new ArrayList<>() {
                        {
                            add(-25371);
                            add(18690);
                        }
                    }, 158061330);
                    put(new ArrayList<>() {
                        {
                            add(17872);
                            add(-22878);
                        }
                    }, 204437808);
                    put(new ArrayList<>() {
                        {
                            add(-32508);
                            add(3563);
                        }
                    }, 16546572);
                    put(new ArrayList<>() {
                        {
                            add(-31456);
                            add(-1461);
                        }
                    }, 45957216);
                    put(new ArrayList<>() {
                        {
                            add(-12737);
                            add(23875);
                        }
                    }, 304095875);
                    put(new ArrayList<>() {
                        {
                            add(19834);
                            add(12472);
                        }
                    }, 123684824);
                    put(new ArrayList<>() {
                        {
                            add(25411);
                            add(8927);
                        }
                    }, 226843997);
                    put(new ArrayList<>() {
                        {
                            add(3687);
                            add(4685);
                        }
                    }, 17273595);
                    put(new ArrayList<>() {
                        {
                            add(-7162);
                            add(-25240);
                        }
                    }, 90384440);
                    put(new ArrayList<>() {
                        {
                            add(-21960);
                            add(-25206);
                        }
                    }, 92253960);
                    put(new ArrayList<>() {
                        {
                            add(-20243);
                            add(12539);
                        }
                    }, 253826977);
                    put(new ArrayList<>() {
                        {
                            add(16415);
                            add(31077);
                        }
                    }, 510128955);
                    put(new ArrayList<>() {
                        {
                            add(26399);
                            add(21996);
                        }
                    }, 580672404);
                    put(new ArrayList<>() {
                        {
                            add(2233);
                            add(-14355);
                        }
                    }, 100485);
                    put(new ArrayList<>() {
                        {
                            add(-31181);
                            add(-12635);
                        }
                    }, 393971935);
                    put(new ArrayList<>() {
                        {
                            add(-10701);
                            add(-27285);
                        }
                    }, 97325595);
                    put(new ArrayList<>() {
                        {
                            add(32335);
                            add(-31987);
                        }
                    }, 35665505);
                    put(new ArrayList<>() {
                        {
                            add(5187);
                            add(5984);
                        }
                    }, 31039008);
                    put(new ArrayList<>() {
                        {
                            add(-1413);
                            add(24643);
                        }
                    }, 34820559);
                    put(new ArrayList<>() {
                        {
                            add(19616);
                            add(14867);
                        }
                    }, 291631072);
                    put(new ArrayList<>() {
                        {
                            add(6599);
                            add(-30812);
                        }
                    }, 203328388);
                    put(new ArrayList<>() {
                        {
                            add(-1002);
                            add(96);
                        }
                    }, 16032);
                    put(new ArrayList<>() {
                        {
                            add(-17734);
                            add(6237);
                        }
                    }, 110606958);
                    put(new ArrayList<>() {
                        {
                            add(5890);
                            add(-14320);
                        }
                    }, 8434480);
                    put(new ArrayList<>() {
                        {
                            add(-32556);
                            add(-32211);
                        }
                    }, 349553772);
                    put(new ArrayList<>() {
                        {
                            add(17204);
                            add(3278);
                        }
                    }, 2563396);
                    put(new ArrayList<>() {
                        {
                            add(-13354);
                            add(-30276);
                        }
                    }, 202152852);
                    put(new ArrayList<>() {
                        {
                            add(-5733);
                            add(3238);
                        }
                    }, 18563454);
                    put(new ArrayList<>() {
                        {
                            add(-3886);
                            add(-4214);
                        }
                    }, 8187802);
                    put(new ArrayList<>() {
                        {
                            add(10356);
                            add(17340);
                        }
                    }, 14964420);
                    put(new ArrayList<>() {
                        {
                            add(21789);
                            add(11263);
                        }
                    }, 245409507);
                    put(new ArrayList<>() {
                        {
                            add(10397);
                            add(-5491);
                        }
                    }, 57089927);
                    put(new ArrayList<>() {
                        {
                            add(14551);
                            add(-21863);
                        }
                    }, 318128513);
                    put(new ArrayList<>() {
                        {
                            add(26550);
                            add(-3411);
                        }
                    }, 10062450);
                    put(new ArrayList<>() {
                        {
                            add(-19334);
                            add(-24002);
                        }
                    }, 232027334);
                    put(new ArrayList<>() {
                        {
                            add(-14522);
                            add(18886);
                        }
                    }, 137131246);
                    put(new ArrayList<>() {
                        {
                            add(26063);
                            add(-31483);
                        }
                    }, 820541429);
                    put(new ArrayList<>() {
                        {
                            add(-22682);
                            add(-19928);
                        }
                    }, 226003448);
                    put(new ArrayList<>() {
                        {
                            add(2283);
                            add(-142);
                        }
                    }, 324186);
                    put(new ArrayList<>() {
                        {
                            add(-16124);
                            add(-29731);
                        }
                    }, 479382644);
                    put(new ArrayList<>() {
                        {
                            add(-1783);
                            add(731);
                        }
                    }, 1303373);
                    put(new ArrayList<>() {
                        {
                            add(-20988);
                            add(-7884);
                        }
                    }, 4596372);
                    put(new ArrayList<>() {
                        {
                            add(3051);
                            add(-28591);
                        }
                    }, 87231141);
                    put(new ArrayList<>() {
                        {
                            add(14505);
                            add(2490);
                        }
                    }, 2407830);
                    put(new ArrayList<>() {
                        {
                            add(-16051);
                            add(-28586);
                        }
                    }, 458833886);
                    put(new ArrayList<>() {
                        {
                            add(9245);
                            add(-12378);
                        }
                    }, 114434610);
                    put(new ArrayList<>() {
                        {
                            add(-12896);
                            add(5171);
                        }
                    }, 66685216);
                    put(new ArrayList<>() {
                        {
                            add(32567);
                            add(10176);
                        }
                    }, 331401792);
                    put(new ArrayList<>() {
                        {
                            add(13922);
                            add(26159);
                        }
                    }, 364185598);
                    put(new ArrayList<>() {
                        {
                            add(-9681);
                            add(-17243);
                        }
                    }, 166929483);
                    put(new ArrayList<>() {
                        {
                            add(17863);
                            add(-3172);
                        }
                    }, 56661436);
                    put(new ArrayList<>() {
                        {
                            add(-16498);
                            add(12824);
                        }
                    }, 105785176);
                    put(new ArrayList<>() {
                        {
                            add(17409);
                            add(16777);
                        }
                    }, 292070793);
                    put(new ArrayList<>() {
                        {
                            add(3437);
                            add(8035);
                        }
                    }, 27616295);
                    put(new ArrayList<>() {
                        {
                            add(-29404);
                            add(-1100);
                        }
                    }, 8086100);
                    put(new ArrayList<>() {
                        {
                            add(-8247);
                            add(-29771);
                        }
                    }, 245521437);
                    put(new ArrayList<>() {
                        {
                            add(-9160);
                            add(19575);
                        }
                    }, 35861400);
                    put(new ArrayList<>() {
                        {
                            add(6378);
                            add(-28656);
                        }
                    }, 30461328);
                    put(new ArrayList<>() {
                        {
                            add(16451);
                            add(-16671);
                        }
                    }, 274254621);
                    put(new ArrayList<>() {
                        {
                            add(17128);
                            add(16334);
                        }
                    }, 139884376);
                    put(new ArrayList<>() {
                        {
                            add(-20825);
                            add(-25523);
                        }
                    }, 531516475);
                    put(new ArrayList<>() {
                        {
                            add(17625);
                            add(-13744);
                        }
                    }, 242238000);
                    put(new ArrayList<>() {
                        {
                            add(-11957);
                            add(24352);
                        }
                    }, 291176864);
                    put(new ArrayList<>() {
                        {
                            add(1607);
                            add(1843);
                        }
                    }, 2961701);
                    put(new ArrayList<>() {
                        {
                            add(374);
                            add(-18030);
                        }
                    }, 3371610);
                    put(new ArrayList<>() {
                        {
                            add(24546);
                            add(-7477);
                        }
                    }, 183530442);
                    put(new ArrayList<>() {
                        {
                            add(-10554);
                            add(-29380);
                        }
                    }, 155038260);
                    put(new ArrayList<>() {
                        {
                            add(-3527);
                            add(9502);
                        }
                    }, 33513554);
                    put(new ArrayList<>() {
                        {
                            add(-3510);
                            add(-14262);
                        }
                    }, 8343270);
                    put(new ArrayList<>() {
                        {
                            add(-14863);
                            add(28212);
                        }
                    }, 419314956);
                    put(new ArrayList<>() {
                        {
                            add(11762);
                            add(-4540);
                        }
                    }, 26699740);
                    put(new ArrayList<>() {
                        {
                            add(24235);
                            add(24226);
                        }
                    }, 587117110);
                    put(new ArrayList<>() {
                        {
                            add(13529);
                            add(28363);
                        }
                    }, 383723027);
                    put(new ArrayList<>() {
                        {
                            add(10978);
                            add(-17943);
                        }
                    }, 196978254);
                    put(new ArrayList<>() {
                        {
                            add(-16540);
                            add(26360);
                        }
                    }, 21799720);
                    put(new ArrayList<>() {
                        {
                            add(-4967);
                            add(15791);
                        }
                    }, 78433897);
                    put(new ArrayList<>() {
                        {
                            add(-7039);
                            add(-576);
                        }
                    }, 4054464);
                    put(new ArrayList<>() {
                        {
                            add(19504);
                            add(19883);
                        }
                    }, 387798032);
                    put(new ArrayList<>() {
                        {
                            add(-30028);
                            add(-19723);
                        }
                    }, 592242244);
                    put(new ArrayList<>() {
                        {
                            add(-26143);
                            add(10328);
                        }
                    }, 270004904);
                    put(new ArrayList<>() {
                        {
                            add(-9268);
                            add(23117);
                        }
                    }, 214248356);
                    put(new ArrayList<>() {
                        {
                            add(17945);
                            add(18418);
                        }
                    }, 330511010);
                    put(new ArrayList<>() {
                        {
                            add(10896);
                            add(27045);
                        }
                    }, 98227440);
                    put(new ArrayList<>() {
                        {
                            add(-29573);
                            add(-2365);
                        }
                    }, 69940145);
                    put(new ArrayList<>() {
                        {
                            add(-4074);
                            add(-15365);
                        }
                    }, 8942430);
                    put(new ArrayList<>() {
                        {
                            add(19170);
                            add(-22230);
                        }
                    }, 4734990);
                    put(new ArrayList<>() {
                        {
                            add(-15645);
                            add(30334);
                        }
                    }, 474575430);
                    put(new ArrayList<>() {
                        {
                            add(27549);
                            add(30079);
                        }
                    }, 828646371);
                    put(new ArrayList<>() {
                        {
                            add(30367);
                            add(-24560);
                        }
                    }, 745813520);
                    put(new ArrayList<>() {
                        {
                            add(-31033);
                            add(-15130);
                        }
                    }, 469529290);
                    put(new ArrayList<>() {
                        {
                            add(5245);
                            add(-5006);
                        }
                    }, 26256470);
                    put(new ArrayList<>() {
                        {
                            add(20284);
                            add(15703);
                        }
                    }, 318519652);
                    put(new ArrayList<>() {
                        {
                            add(-16843);
                            add(-29174);
                        }
                    }, 491377682);
                    put(new ArrayList<>() {
                        {
                            add(-30147);
                            add(-23703);
                        }
                    }, 238191447);
                    put(new ArrayList<>() {
                        {
                            add(-9841);
                            add(-26797);
                        }
                    }, 263709277);
                    put(new ArrayList<>() {
                        {
                            add(25255);
                            add(-18233);
                        }
                    }, 460474415);
                    put(new ArrayList<>() {
                        {
                            add(32648);
                            add(13532);
                        }
                    }, 110448184);
                    put(new ArrayList<>() {
                        {
                            add(24709);
                            add(-19603);
                        }
                    }, 484370527);
                    put(new ArrayList<>() {
                        {
                            add(-7585);
                            add(-576);
                        }
                    }, 4368960);
                    put(new ArrayList<>() {
                        {
                            add(26347);
                            add(-13764);
                        }
                    }, 362640108);
                    put(new ArrayList<>() {
                        {
                            add(-18067);
                            add(-8567);
                        }
                    }, 154779989);
                    put(new ArrayList<>() {
                        {
                            add(13582);
                            add(1351);
                        }
                    }, 18349282);
                    put(new ArrayList<>() {
                        {
                            add(-25649);
                            add(-13291);
                        }
                    }, 340900859);
                    put(new ArrayList<>() {
                        {
                            add(-29805);
                            add(15581);
                        }
                    }, 464391705);
                    put(new ArrayList<>() {
                        {
                            add(11852);
                            add(-31119);
                        }
                    }, 368822388);
                    put(new ArrayList<>() {
                        {
                            add(-1577);
                            add(16581);
                        }
                    }, 26148237);
                    put(new ArrayList<>() {
                        {
                            add(-8095);
                            add(-30103);
                        }
                    }, 243683785);
                    put(new ArrayList<>() {
                        {
                            add(-12017);
                            add(25475);
                        }
                    }, 306133075);
                    put(new ArrayList<>() {
                        {
                            add(-26518);
                            add(27333);
                        }
                    }, 724816494);
                    put(new ArrayList<>() {
                        {
                            add(-21256);
                            add(26587);
                        }
                    }, 565133272);
                    put(new ArrayList<>() {
                        {
                            add(-11910);
                            add(4212);
                        }
                    }, 8360820);
                    put(new ArrayList<>() {
                        {
                            add(-18603);
                            add(-22797);
                        }
                    }, 47121399);
                    put(new ArrayList<>() {
                        {
                            add(-4585);
                            add(4843);
                        }
                    }, 22205155);
                    put(new ArrayList<>() {
                        {
                            add(-24759);
                            add(-242);
                        }
                    }, 5991678);
                    put(new ArrayList<>() {
                        {
                            add(3011);
                            add(5503);
                        }
                    }, 16569533);
                    put(new ArrayList<>() {
                        {
                            add(-14365);
                            add(11314);
                        }
                    }, 162525610);
                    put(new ArrayList<>() {
                        {
                            add(26636);
                            add(9946);
                        }
                    }, 132460828);
                    put(new ArrayList<>() {
                        {
                            add(-14264);
                            add(2847);
                        }
                    }, 40609608);
                    put(new ArrayList<>() {
                        {
                            add(28811);
                            add(-29237);
                        }
                    }, 842347207);
                    put(new ArrayList<>() {
                        {
                            add(-14643);
                            add(2486);
                        }
                    }, 36402498);
                    put(new ArrayList<>() {
                        {
                            add(32437);
                            add(-24131);
                        }
                    }, 782737247);
                    put(new ArrayList<>() {
                        {
                            add(8000);
                            add(-19819);
                        }
                    }, 158552000);
                    put(new ArrayList<>() {
                        {
                            add(-4445);
                            add(-22967);
                        }
                    }, 14584045);
                    put(new ArrayList<>() {
                        {
                            add(-5532);
                            add(-16050);
                        }
                    }, 14798100);
                    put(new ArrayList<>() {
                        {
                            add(15600);
                            add(-11447);
                        }
                    }, 178573200);
                    put(new ArrayList<>() {
                        {
                            add(17816);
                            add(22316);
                        }
                    }, 99395464);
                    put(new ArrayList<>() {
                        {
                            add(459);
                            add(15982);
                        }
                    }, 7335738);
                    put(new ArrayList<>() {
                        {
                            add(11323);
                            add(-12082);
                        }
                    }, 136804486);
                    put(new ArrayList<>() {
                        {
                            add(23673);
                            add(24496);
                        }
                    }, 579893808);
                    put(new ArrayList<>() {
                        {
                            add(12813);
                            add(-13109);
                        }
                    }, 167965617);
                    put(new ArrayList<>() {
                        {
                            add(-5691);
                            add(-23735);
                        }
                    }, 135075885);
                    put(new ArrayList<>() {
                        {
                            add(24997);
                            add(4364);
                        }
                    }, 109086908);
                    put(new ArrayList<>() {
                        {
                            add(17625);
                            add(15089);
                        }
                    }, 265943625);
                    put(new ArrayList<>() {
                        {
                            add(1780);
                            add(17302);
                        }
                    }, 15398780);
                    put(new ArrayList<>() {
                        {
                            add(-28204);
                            add(-6030);
                        }
                    }, 85035060);
                    put(new ArrayList<>() {
                        {
                            add(-18155);
                            add(-27152);
                        }
                    }, 492944560);
                    put(new ArrayList<>() {
                        {
                            add(15747);
                            add(27557);
                        }
                    }, 433940079);
                    put(new ArrayList<>() {
                        {
                            add(28391);
                            add(-7954);
                        }
                    }, 225822014);
                    put(new ArrayList<>() {
                        {
                            add(-30557);
                            add(3758);
                        }
                    }, 114833206);
                    put(new ArrayList<>() {
                        {
                            add(-25392);
                            add(14036);
                        }
                    }, 89100528);
                    put(new ArrayList<>() {
                        {
                            add(20993);
                            add(7956);
                        }
                    }, 167020308);
                    put(new ArrayList<>() {
                        {
                            add(23572);
                            add(14925);
                        }
                    }, 351812100);
                    put(new ArrayList<>() {
                        {
                            add(27498);
                            add(-11583);
                        }
                    }, 106169778);
                    put(new ArrayList<>() {
                        {
                            add(-24089);
                            add(-4984);
                        }
                    }, 120059576);
                    put(new ArrayList<>() {
                        {
                            add(6480);
                            add(13973);
                        }
                    }, 90545040);
                    put(new ArrayList<>() {
                        {
                            add(23512);
                            add(30925);
                        }
                    }, 727108600);
                    put(new ArrayList<>() {
                        {
                            add(-26360);
                            add(795);
                        }
                    }, 4191240);
                    put(new ArrayList<>() {
                        {
                            add(15376);
                            add(7926);
                        }
                    }, 60935088);
                    put(new ArrayList<>() {
                        {
                            add(-882);
                            add(-23321);
                        }
                    }, 20569122);
                    put(new ArrayList<>() {
                        {
                            add(-7977);
                            add(-10493);
                        }
                    }, 83702661);
                    put(new ArrayList<>() {
                        {
                            add(5213);
                            add(-25595);
                        }
                    }, 133426735);
                    put(new ArrayList<>() {
                        {
                            add(-9526);
                            add(-2215);
                        }
                    }, 21100090);
                    put(new ArrayList<>() {
                        {
                            add(-1782);
                            add(4166);
                        }
                    }, 3711906);
                    put(new ArrayList<>() {
                        {
                            add(19024);
                            add(-11292);
                        }
                    }, 53704752);
                    put(new ArrayList<>() {
                        {
                            add(26267);
                            add(-23856);
                        }
                    }, 626625552);
                    put(new ArrayList<>() {
                        {
                            add(4996);
                            add(17143);
                        }
                    }, 85646428);
                    put(new ArrayList<>() {
                        {
                            add(-28919);
                            add(31017);
                        }
                    }, 896980623);
                    put(new ArrayList<>() {
                        {
                            add(-17499);
                            add(20888);
                        }
                    }, 365519112);
                    put(new ArrayList<>() {
                        {
                            add(674);
                            add(-8892);
                        }
                    }, 2996604);
                    put(new ArrayList<>() {
                        {
                            add(-79);
                            add(18126);
                        }
                    }, 1431954);
                    put(new ArrayList<>() {
                        {
                            add(32416);
                            add(-19288);
                        }
                    }, 78154976);
                    put(new ArrayList<>() {
                        {
                            add(-10931);
                            add(8089);
                        }
                    }, 88420859);
                    put(new ArrayList<>() {
                        {
                            add(18283);
                            add(-11272);
                        }
                    }, 206085976);
                    put(new ArrayList<>() {
                        {
                            add(-3773);
                            add(17465);
                        }
                    }, 9413635);
                    put(new ArrayList<>() {
                        {
                            add(5768);
                            add(-11092);
                        }
                    }, 15994664);
                    put(new ArrayList<>() {
                        {
                            add(-4602);
                            add(-18785);
                        }
                    }, 6649890);
                    put(new ArrayList<>() {
                        {
                            add(-3720);
                            add(2269);
                        }
                    }, 8440680);
                    put(new ArrayList<>() {
                        {
                            add(-8173);
                            add(-14397);
                        }
                    }, 117666681);
                    put(new ArrayList<>() {
                        {
                            add(11511);
                            add(21419);
                        }
                    }, 246554109);
                    put(new ArrayList<>() {
                        {
                            add(-18515);
                            add(27050);
                        }
                    }, 100166150);
                    put(new ArrayList<>() {
                        {
                            add(-20132);
                            add(-1243);
                        }
                    }, 25024076);
                    put(new ArrayList<>() {
                        {
                            add(-3712);
                            add(-14846);
                        }
                    }, 27554176);
                    put(new ArrayList<>() {
                        {
                            add(7374);
                            add(-7180);
                        }
                    }, 26472660);
                    put(new ArrayList<>() {
                        {
                            add(6075);
                            add(10868);
                        }
                    }, 66023100);
                    put(new ArrayList<>() {
                        {
                            add(750);
                            add(-23248);
                        }
                    }, 8718000);
                    put(new ArrayList<>() {
                        {
                            add(19518);
                            add(9539);
                        }
                    }, 186182202);
                    put(new ArrayList<>() {
                        {
                            add(12967);
                            add(-1720);
                        }
                    }, 22303240);
                    put(new ArrayList<>() {
                        {
                            add(24534);
                            add(-20600);
                        }
                    }, 252700200);
                    put(new ArrayList<>() {
                        {
                            add(31776);
                            add(3682);
                        }
                    }, 58499616);
                    put(new ArrayList<>() {
                        {
                            add(11233);
                            add(-4450);
                        }
                    }, 49986850);
                    put(new ArrayList<>() {
                        {
                            add(-7128);
                            add(14588);
                        }
                    }, 25995816);
                    put(new ArrayList<>() {
                        {
                            add(-20227);
                            add(8974);
                        }
                    }, 181517098);
                    put(new ArrayList<>() {
                        {
                            add(-20230);
                            add(19345);
                        }
                    }, 78269870);
                    put(new ArrayList<>() {
                        {
                            add(18498);
                            add(7478);
                        }
                    }, 69164022);
                    put(new ArrayList<>() {
                        {
                            add(-31593);
                            add(3670);
                        }
                    }, 115946310);
                    put(new ArrayList<>() {
                        {
                            add(2755);
                            add(-17953);
                        }
                    }, 49460515);
                    put(new ArrayList<>() {
                        {
                            add(16925);
                            add(-18633);
                        }
                    }, 315363525);
                    put(new ArrayList<>() {
                        {
                            add(2259);
                            add(-8355);
                        }
                    }, 6291315);
                    put(new ArrayList<>() {
                        {
                            add(-1021);
                            add(16530);
                        }
                    }, 16877130);
                    put(new ArrayList<>() {
                        {
                            add(-7122);
                            add(-3876);
                        }
                    }, 4600812);
                    put(new ArrayList<>() {
                        {
                            add(-21866);
                            add(-6899);
                        }
                    }, 150853534);
                    /* END AUTOGENERATED CODE */
                }
            };
}
